BACKLOG-15711: Basic tests (#795)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -58,16 +58,29 @@ jobs:
             echo "$DOCKERHUB_LOGIN"
             echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_LOGIN" --password-stdin
       - run:
+          name: Store Jahia version
+          command: |
+            mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec > jahia.version
+            cp jahia.version image.tag
+      - run:
+          name: Determine tag
+          command: |
+            if [ "false" = "<<parameters.is_pull_request>>" ]; then
+              cp jahia.version image.tag
+            else
+              echo "${CIRCLE_BRANCH}" > image.tag
+            fi
+      - run:
           # TODO For now I just replaced the Bamboo build number by the CircleCI build number
           name: Build package and load all dependencies into local Maven repository
           command: |
-            mvn -s .circleci/.circleci.settings.xml -e clean package de.qaware.maven:go-offline-maven-plugin:resolve-dependencies \
+            mvn -s .circleci/.circleci.settings.xml -e -Dimage.tag=`cat image.tag` clean package de.qaware.maven:go-offline-maven-plugin:resolve-dependencies \
                -Pgwt-production,unit-tests,docker -Dbamboo.buildNumber=$CIRCLE_BUILD_NUM
       - run:
           # TODO For now I just replaced the Bamboo build number by the CircleCI build number
           name: Compile GWT development
           working_directory: ~/source/gwt
-          command: mvn -s ../.circleci/.circleci.settings.xml -e clean package -Pgwt-development -Dbamboo.buildNumber=$CIRCLE_BUILD_NUM
+          command: mvn -s ../.circleci/.circleci.settings.xml -e -Dimage.tag=`cat image.tag` clean package -Pgwt-development -Dbamboo.buildNumber=$CIRCLE_BUILD_NUM
       - unless:
           condition: <<parameters.is_pull_request>>
           steps:
@@ -76,7 +89,18 @@ jobs:
                 # TODO For now I just replaced the Bamboo build number by the CircleCI build number
                 name: Deploy artifacts to server repository
                 working_directory: ~/source/docker-jahia-core
-                command: mvn -s ../.circleci/.circleci.settings.xml -e deploy -Dbamboo.buildNumber=$CIRCLE_BUILD_NUM
+                command: mvn -s ../.circleci/.circleci.settings.xml -e -Dimage.tag=`cat image.tag` deploy -Dbamboo.buildNumber=$CIRCLE_BUILD_NUM
+      - when:
+          condition: <<parameters.is_pull_request>>
+          steps:
+            - run:
+                # This is only done on PR, as master is pushed with mvn deploy in "Deploy artifacts to server repository"
+                name: Push PR Docker image
+                command: |
+                  docker push jahia/jahia-core:`cat image.tag`
+      - run:
+          name: Store docker image
+          command: docker save -o image.tar jahia/jahia-core:`cat image.tag`
       - save_cache:
           paths:
             - ~/.m2
@@ -103,6 +127,114 @@ jobs:
 #          working_directory: ~/source/docker
 #          command: |
 #            mvn -s ../.circleci/.circleci.settings.xml -e clean package de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
+
+  integration_tests:
+    <<: *workdir
+    docker: # run the steps with Docker
+      - image: circleci/openjdk:8-jdk-stretch
+    # Available types: medium, large, xlarge, 2xlarge https://circleci.com/docs/2.0/configuration-reference/#machine-executor-linux
+    resource_class: xlarge
+    parameters:
+      TESTS_IMAGE:
+        type: string
+        default: "jahia/jahia-core_test"
+      BUILD_TESTSIMAGE:
+        type: boolean
+        default: true
+      TESTS_PATH:
+        type: string
+        default: "docker-tests/"
+    steps:
+      - *attach-workspace
+      - setup_remote_docker:
+          version: 19.03.13
+          docker_layer_caching: true
+      - run:
+          name:
+            Prepare artifacts
+            # This command copy the various build artifacts into the /tests/ folder to be later
+            # used by jahia-cli to provision Jahia for testing
+          command: |
+            if [ ! -d << parameters.TESTS_PATH >>artifacts ]; then
+              mkdir -p << parameters.TESTS_PATH >>artifacts
+            fi
+      - run:
+          name: Docker login
+          # This is needed to fetch private docker images (such as Jahia snapshot)
+          command: |
+            echo "$DOCKERHUB_LOGIN"
+            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_LOGIN" --password-stdin
+      - run:
+          name: Load docker image
+          command: docker load -i image.tar
+      - run:
+          name: Spin-up dockerized jahia
+          # At that point we're only sprinning up Jahia and its runtime dependencies,
+          # We are not starting the tests yet since we first want to build the test container (or run from a previously built container) \
+          # Checking the presence of the .env file is there because it's needed by the tests, but to not break ci/cd if variables
+          #   are added to the compose file but not to the environment variables in circleci config.yml
+          command: |
+            set -e
+            cd << parameters.TESTS_PATH >>
+            if [[ ! -e .env ]]; then
+              mv .env.example .env
+            fi
+            echo JAHIA_IMAGE=jahia/jahia-core:`cat ../image.tag` >> .env
+            docker-compose -f docker-compose.yml up -d jahia
+          no_output_timeout: 2h
+      - run:
+          # We want to build the test image from scratch with any code change (since that code change could be in the tests themselves)
+          name: Build << parameters.TESTS_IMAGE >> image
+          command: |
+            if [ << parameters.BUILD_TESTSIMAGE >> == true ]; then
+              cd << parameters.TESTS_PATH >>
+              docker build -t << parameters.TESTS_IMAGE >> .
+              docker save -o tests_image.tar << parameters.TESTS_IMAGE >>
+            fi
+      - run:
+          name: Execute tests
+          # Running the tests, note that the reports are copied at the end of execution
+          # We don't need (nor want) this actual step to fail
+          # Failure is determined by counting the number of failed tests in the output report
+          # Note: the timeout env vars are added to address this: https://github.com/docker/compose/issues/3927
+          command: |
+            set -e
+            cd << parameters.TESTS_PATH >>
+            export DOCKER_CLIENT_TIMEOUT=120
+            export COMPOSE_HTTP_TIMEOUT=120
+            docker-compose -f docker-compose.yml up cypress
+            docker cp cypress:/tmp/results ./artifacts
+          no_output_timeout: 2h
+          environment:
+            TESTS_IMAGE: << parameters.TESTS_IMAGE >>:latest
+      - run:
+          name: Export jahia logs
+          when: always
+          command: |
+            set -e
+            cd << parameters.TESTS_PATH >>
+            docker logs jahia > ./artifacts/results/jahia.log
+            docker logs cypress > ./artifacts/results/cypress.log
+      # This is not needed since cypress is going to terminat on failure with exit code 1
+      - run:
+          name: Analyze Test results
+          when: always
+          # This looks at the report and fail the job if one of the test has failed
+          command: |
+            cd << parameters.TESTS_PATH >>
+            if [[ ! -e ./artifacts/results/test_success ]]; then
+              echo "More than one failure found, sending exit signal"
+              exit 1
+            fi
+      - store_test_results:
+          path: << parameters.TESTS_PATH >>artifacts/results/xml_reports
+      - run:
+          name: remove xml results folder
+          command: rm -rf << parameters.TESTS_PATH >>artifacts/results/xml_reports
+      - store_artifacts:
+          path: << parameters.TESTS_PATH >>artifacts/results
+      - *persist-workspace
+
 
   sonar:
     parameters:
@@ -200,6 +332,11 @@ workflows:
           context: QA_ENVIRONMENT
           requires:
             - PR Checkout
+      - integration_tests:
+          name: Integration tests
+          context: QA_ENVIRONMENT
+          requires:
+            - PR Build Jahia
       - sonar:
           name: PR Sonar analysis
           is_pull_request: true
@@ -221,6 +358,11 @@ workflows:
           context: QA_ENVIRONMENT
           requires:
             - checkout
+      - integration_tests:
+          name: Integration tests
+          context: QA_ENVIRONMENT
+          requires:
+            - Build Jahia
       - sonar:
           name: Sonar analysis
           is_pull_request: false
